title: Trang cá nhân của Tôi
description: Portfolio / Blog
# Chọn 1 theme hỗ trợ remote_theme (ví dụ "pages-themes/cayman@v0.2.0")
remote_theme: pages-themes/cayman@v0.2.0

# Tuỳ chọn (hiện menu, link mạng xã hội…)
show_downloads: false
google_analytics:
github:
  is_project_page: false
